import enum

class ErrorCode(enum.IntEnum):
    PA_OK = 0
    PA_ERR_ACCESS = 1
    PA_ERR_COMMAND = 2
    PA_ERR_INVALID = 3
    PA_ERR_EXIST = 4
    PA_ERR_NOENTITY = 5
    PA_ERR_CONNECTIONREFUSED = 6
    PA_ERR_PROTOCOL = 7
    PA_ERR_TIMEOUT = 8
    PA_ERR_AUTHKEY = 9
    PA_ERR_INTERNAL = 10
    PA_ERR_CONNECTIONTERMINATED = 11
    PA_ERR_KILLED = 12
    PA_ERR_INVALIDSERVER = 13
    PA_ERR_MODINITFAILED = 14
    PA_ERR_BADSTATE = 15
    PA_ERR_NODATA = 16
    PA_ERR_VERSION = 17
    PA_ERR_TOOLARGE = 18
    PA_ERR_NOTSUPPORTED = 19
    PA_ERR_UNKNOWN = 20
    PA_ERR_NOEXTENSION = 21
    PA_ERR_OBSOLETE = 22
    PA_ERR_NOTIMPLEMENTED = 23
    PA_ERR_FORKED = 24
    PA_ERR_IO = 25
    PA_ERR_BUSY = 26
    PA_ERR_MAX = 27
