structure = [
    ('index', 'u32'),
    ('name', 'string'),
    ('description', 'string'),
    ('sample_spec', 'sample_spec'),
    ('channel_map', 'channel_map'),
    ('owner_module', 'u32'),
    ('volume', 'cvolume'),
    ('mute', 'boolean'),
    ('monitor_source', 'u32'),
    ('monitor_source_name', 'string'),
    ('latency', 'usec'),
    ('driver', 'string'),
    ('flags', 'u32'),
    ('proplist', 'proplist'),
    ('configured_latency', 'usec'),
    ('base_volume', 'volume'),
    ('state', 'u32'),
    ('n_volume_steps', 'u32'),
    ('card', 'u32'),
    ('n_ports', 'u32'),
    ('ports', 'ports'),
    ('ap', 'ap'),
    ('formats', 'formats'),
]
